// Generated by scripts/ingest-creative-cases.mjs. Do not edit manually.
export const CREATIVE_STORY_CASES = [] as const;

export const CREATIVE_STORY_CASE_META = {
    "generatedAt": "2026-07-10T14:57:42.659Z",
    "caseCount": 0,
    "activeCaseCount": 0,
    "candidateCaseCount": 0,
    "mode": "empty"
} as const;
