// Generated by scripts/ingest-creative-knowledge.mjs. Do not edit manually.
export const CREATIVE_IMPORTED_KNOWLEDGE_CONTEXT = "";

export const CREATIVE_IMPORTED_KNOWLEDGE_META = {
    "generatedAt": "2026-07-06T22:28:56.471Z",
    "sourceCount": 0,
    "cardCount": 0,
    "mode": "empty",
    "sources": []
} as const;
