// Generated by scripts/ingest-creative-knowledge.mjs. Do not edit manually.
export const CREATIVE_IMPORTED_KNOWLEDGE_CONTEXT = "";

export const CREATIVE_IMPORTED_KNOWLEDGE_CARDS = [] as const;

export const CREATIVE_IMPORTED_KNOWLEDGE_META = {
    "generatedAt": "2026-07-10T14:47:33.096Z",
    "sourceCount": 0,
    "cardCount": 0,
    "activeCardCount": 0,
    "candidateCardCount": 0,
    "mode": "empty",
    "sources": []
} as const;
